import React from 'react';
import { Container, Sidebar, Main } from './styles';

import Profile from './Profile';
import Filter from './Filter';
import Repositories from './Repositories';
import { getLangsFrom } from '../../services/api';

export default function RepositoriesPage() {
  const userMock = {
    login: 'HalefAlmeida',
    id: 38929215,
    node_id: 'MDQ6VXNlcjM4OTI5MjE1',
    avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HalefAlmeida',
    html_url: 'https://github.com/HalefAlmeida',
    followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
    following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
    gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
    organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
    repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
    events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
    received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    name: 'Halef Dorigan',
    company: 'Predialize',
    blog: 'https://www.nortwest.com.br/',
    location: 'Umuarama/PR - BR',
    email: null,
    hireable: null,
    bio: 'Owner at Nortwest Developer\r\n💻 FullStack Developer at @predialize \r\n',
    twitter_username: null,
    public_repos: 14,
    public_gists: 0,
    followers: 20,
    following: 31,
    created_at: '2018-05-03T01:00:39Z',
    updated_at: '2025-07-23T11:21:14Z',
  };

  const repositoriesMock = [
    {
      id: 471163732,
      node_id: 'R_kgDOHBVjVA',
      name: 'angulardevweek',
      full_name: 'HalefAlmeida/angulardevweek',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/angulardevweek',
      description:
        'Aplicação desenvolvida durante a Philips Dev Week, dos dias 08/03/2022 ao dia 11/03/2022.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/angulardevweek/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/angulardevweek/deployments',
      created_at: '2022-03-17T22:37:34Z',
      updated_at: '2022-03-17T22:38:02Z',
      pushed_at: '2022-03-17T22:37:40Z',
      git_url: 'git://github.com/HalefAlmeida/angulardevweek.git',
      ssh_url: 'git@github.com:HalefAlmeida/angulardevweek.git',
      clone_url: 'https://github.com/HalefAlmeida/angulardevweek.git',
      svn_url: 'https://github.com/HalefAlmeida/angulardevweek',
      homepage: '',
      size: 205,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 1065490515,
      node_id: 'R_kgDOP4IYUw',
      name: 'api-github-dev',
      full_name: 'HalefAlmeida/api-github-dev',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/api-github-dev',
      description: 'React Project to retrieve user data from Github Api.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/api-github-dev/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/api-github-dev/deployments',
      created_at: '2025-09-27T20:47:46Z',
      updated_at: '2025-09-29T00:25:02Z',
      pushed_at: '2025-09-29T00:24:59Z',
      git_url: 'git://github.com/HalefAlmeida/api-github-dev.git',
      ssh_url: 'git@github.com:HalefAlmeida/api-github-dev.git',
      clone_url: 'https://github.com/HalefAlmeida/api-github-dev.git',
      svn_url: 'https://github.com/HalefAlmeida/api-github-dev',
      homepage: null,
      size: 218,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 371863388,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzE4NjMzODg=',
      name: 'bootcamp',
      full_name: 'HalefAlmeida/bootcamp',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/bootcamp',
      description: 'Projeto de back-end em Java criado para o bootcamp DIO - Santander',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/bootcamp',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/hooks',
      issue_events_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp/deployments',
      created_at: '2021-05-29T02:35:37Z',
      updated_at: '2021-05-29T03:07:29Z',
      pushed_at: '2021-05-29T03:07:27Z',
      git_url: 'git://github.com/HalefAlmeida/bootcamp.git',
      ssh_url: 'git@github.com:HalefAlmeida/bootcamp.git',
      clone_url: 'https://github.com/HalefAlmeida/bootcamp.git',
      svn_url: 'https://github.com/HalefAlmeida/bootcamp',
      homepage:
        'https://projeto-backend-bootcamp.herokuapp.com/bootcamp/swagger-ui/index.html?configUrl=/bootcamp/v3/api-docs/swagger-config',
      size: 15,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 474203421,
      node_id: 'R_kgDOHEPFHQ',
      name: 'bootcamp-digital-innovation-one-philips',
      full_name: 'HalefAlmeida/bootcamp-digital-innovation-one-philips',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/bootcamp-digital-innovation-one-philips',
      description: 'Anotações, conteúdos e projetos gerados durante o Bootcamp Philips Fullstack',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips',
      forks_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/forks',
      keys_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/collaborators{/collaborator}',
      teams_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/teams',
      hooks_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/issues/events{/number}',
      events_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/events',
      assignees_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/branches{/branch}',
      tags_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/tags',
      blobs_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/git/blobs{/sha}',
      git_tags_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/git/tags{/sha}',
      git_refs_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/git/refs{/sha}',
      trees_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/git/trees{/sha}',
      statuses_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/statuses/{sha}',
      languages_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/languages',
      stargazers_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/stargazers',
      contributors_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/contributors',
      subscribers_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/subscribers',
      subscription_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/subscription',
      commits_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/issues/comments{/number}',
      contents_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/compare/{base}...{head}',
      merges_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/{archive_format}{/ref}',
      downloads_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/downloads',
      issues_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/issues{/number}',
      pulls_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/notifications{?since,all,participating}',
      labels_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/labels{/name}',
      releases_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/releases{/id}',
      deployments_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-digital-innovation-one-philips/deployments',
      created_at: '2022-03-26T00:40:38Z',
      updated_at: '2022-04-14T01:49:22Z',
      pushed_at: '2022-05-05T02:02:57Z',
      git_url: 'git://github.com/HalefAlmeida/bootcamp-digital-innovation-one-philips.git',
      ssh_url: 'git@github.com:HalefAlmeida/bootcamp-digital-innovation-one-philips.git',
      clone_url: 'https://github.com/HalefAlmeida/bootcamp-digital-innovation-one-philips.git',
      svn_url: 'https://github.com/HalefAlmeida/bootcamp-digital-innovation-one-philips',
      homepage: '',
      size: 8501,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 372032897,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzIwMzI4OTc=',
      name: 'bootcamp-homebroker',
      full_name: 'HalefAlmeida/bootcamp-homebroker',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/bootcamp-homebroker',
      description:
        'Aplicação de front-end em Angular para apresentação de ações com integração ao back-end Java.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/events',
      assignees_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/stargazers',
      contributors_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/subscribers',
      subscription_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/issues/comments{/number}',
      contents_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/bootcamp-homebroker/deployments',
      created_at: '2021-05-29T17:27:44Z',
      updated_at: '2021-06-01T01:08:52Z',
      pushed_at: '2021-06-01T01:17:19Z',
      git_url: 'git://github.com/HalefAlmeida/bootcamp-homebroker.git',
      ssh_url: 'git@github.com:HalefAlmeida/bootcamp-homebroker.git',
      clone_url: 'https://github.com/HalefAlmeida/bootcamp-homebroker.git',
      svn_url: 'https://github.com/HalefAlmeida/bootcamp-homebroker',
      homepage: '',
      size: 274,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 471162662,
      node_id: 'R_kgDOHBVfJg',
      name: 'devweek',
      full_name: 'HalefAlmeida/devweek',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/devweek',
      description:
        'API desenvolvida durante a Philips Dev Week, dos dias 08/03/2022 ao dia 11/03/2022.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/devweek',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/devweek/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/devweek/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/devweek/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/devweek/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/devweek/hooks',
      issue_events_url: 'https://api.github.com/repos/HalefAlmeida/devweek/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/devweek/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/devweek/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/devweek/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/devweek/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/devweek/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/devweek/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/devweek/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/devweek/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/devweek/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/devweek/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/devweek/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/devweek/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/devweek/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/devweek/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/devweek/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/devweek/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/devweek/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/devweek/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/devweek/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/devweek/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/devweek/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/devweek/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/devweek/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/devweek/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/devweek/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/devweek/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/devweek/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/devweek/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/devweek/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/devweek/deployments',
      created_at: '2022-03-17T22:32:32Z',
      updated_at: '2022-03-17T22:34:14Z',
      pushed_at: '2022-03-17T22:36:36Z',
      git_url: 'git://github.com/HalefAlmeida/devweek.git',
      ssh_url: 'git@github.com:HalefAlmeida/devweek.git',
      clone_url: 'https://github.com/HalefAlmeida/devweek.git',
      svn_url: 'https://github.com/HalefAlmeida/devweek',
      homepage: null,
      size: 62,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 484182651,
      node_id: 'R_kgDOHNwKew',
      name: 'dino-game',
      full_name: 'HalefAlmeida/dino-game',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/dino-game',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/dino-game',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/dino-game/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/dino-game/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/dino-game/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/dino-game/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/dino-game/deployments',
      created_at: '2022-04-21T19:39:56Z',
      updated_at: '2022-04-21T19:40:08Z',
      pushed_at: '2022-04-21T19:40:05Z',
      git_url: 'git://github.com/HalefAlmeida/dino-game.git',
      ssh_url: 'git@github.com:HalefAlmeida/dino-game.git',
      clone_url: 'https://github.com/HalefAlmeida/dino-game.git',
      svn_url: 'https://github.com/HalefAlmeida/dino-game',
      homepage: null,
      size: 11,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 500635375,
      node_id: 'R_kgDOHdcW7w',
      name: 'dsmovie',
      full_name: 'HalefAlmeida/dsmovie',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/dsmovie',
      description: null,
      fork: true,
      url: 'https://api.github.com/repos/HalefAlmeida/dsmovie',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/dsmovie/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/hooks',
      issue_events_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/dsmovie/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/dsmovie/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/dsmovie/deployments',
      created_at: '2022-06-07T00:27:35Z',
      updated_at: '2022-06-29T23:36:24Z',
      pushed_at: '2022-06-29T23:36:20Z',
      git_url: 'git://github.com/HalefAlmeida/dsmovie.git',
      ssh_url: 'git@github.com:HalefAlmeida/dsmovie.git',
      clone_url: 'https://github.com/HalefAlmeida/dsmovie.git',
      svn_url: 'https://github.com/HalefAlmeida/dsmovie',
      homepage: null,
      size: 727,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
    {
      id: 376967653,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzY5Njc2NTM=',
      name: 'HalefAlmeida',
      full_name: 'HalefAlmeida/HalefAlmeida',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/HalefAlmeida',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/HalefAlmeida/deployments',
      created_at: '2021-06-14T22:05:48Z',
      updated_at: '2022-11-10T20:11:55Z',
      pushed_at: '2024-01-31T14:01:44Z',
      git_url: 'git://github.com/HalefAlmeida/HalefAlmeida.git',
      ssh_url: 'git@github.com:HalefAlmeida/HalefAlmeida.git',
      clone_url: 'https://github.com/HalefAlmeida/HalefAlmeida.git',
      svn_url: 'https://github.com/HalefAlmeida/HalefAlmeida',
      homepage: null,
      size: 14,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 374377968,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNzQzNzc5Njg=',
      name: 'marca-ai',
      full_name: 'HalefAlmeida/marca-ai',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/marca-ai',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/marca-ai',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/marca-ai/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/hooks',
      issue_events_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/marca-ai/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/marca-ai/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/marca-ai/deployments',
      created_at: '2021-06-06T14:14:42Z',
      updated_at: '2021-06-06T14:14:53Z',
      pushed_at: '2021-06-13T15:26:25Z',
      git_url: 'git://github.com/HalefAlmeida/marca-ai.git',
      ssh_url: 'git@github.com:HalefAlmeida/marca-ai.git',
      clone_url: 'https://github.com/HalefAlmeida/marca-ai.git',
      svn_url: 'https://github.com/HalefAlmeida/marca-ai',
      homepage: null,
      size: 158,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 367623253,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNjc2MjMyNTM=',
      name: 'projeto-finance',
      full_name: 'HalefAlmeida/projeto-finance',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/projeto-finance',
      description: 'Projeto para controle de entradas e saídas financeiras.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/projeto-finance/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/projeto-finance/deployments',
      created_at: '2021-05-15T12:14:11Z',
      updated_at: '2021-05-15T12:14:12Z',
      pushed_at: '2021-05-15T12:40:25Z',
      git_url: 'git://github.com/HalefAlmeida/projeto-finance.git',
      ssh_url: 'git@github.com:HalefAlmeida/projeto-finance.git',
      clone_url: 'https://github.com/HalefAlmeida/projeto-finance.git',
      svn_url: 'https://github.com/HalefAlmeida/projeto-finance',
      homepage: null,
      size: 36,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 197171201,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTcxNzEyMDE=',
      name: 'Robo_Cisi',
      full_name: 'HalefAlmeida/Robo_Cisi',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/Robo_Cisi',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/Robo_Cisi/deployments',
      created_at: '2019-07-16T10:16:43Z',
      updated_at: '2023-06-15T21:12:19Z',
      pushed_at: '2019-07-16T10:20:23Z',
      git_url: 'git://github.com/HalefAlmeida/Robo_Cisi.git',
      ssh_url: 'git@github.com:HalefAlmeida/Robo_Cisi.git',
      clone_url: 'https://github.com/HalefAlmeida/Robo_Cisi.git',
      svn_url: 'https://github.com/HalefAlmeida/Robo_Cisi',
      homepage: null,
      size: 102,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Jupyter Notebook',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'develop',
    },
    {
      id: 341363744,
      node_id: 'MDEwOlJlcG9zaXRvcnkzNDEzNjM3NDQ=',
      name: 'SaveMyJob',
      full_name: 'HalefAlmeida/SaveMyJob',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/SaveMyJob',
      description:
        'Aplicação desenvolvida para uso pessoal com o intuito de registrar atividades realizadas durante o dia de forma simples.',
      fork: false,
      url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/SaveMyJob/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/SaveMyJob/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/events',
      assignees_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/assignees{/user}',
      branches_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/SaveMyJob/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/contents/{+path}',
      compare_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/merges',
      archive_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/SaveMyJob/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/SaveMyJob/deployments',
      created_at: '2021-02-22T23:09:35Z',
      updated_at: '2021-05-15T11:26:56Z',
      pushed_at: '2021-03-09T21:37:04Z',
      git_url: 'git://github.com/HalefAlmeida/SaveMyJob.git',
      ssh_url: 'git@github.com:HalefAlmeida/SaveMyJob.git',
      clone_url: 'https://github.com/HalefAlmeida/SaveMyJob.git',
      svn_url: 'https://github.com/HalefAlmeida/SaveMyJob',
      homepage: 'https://savemyjob-2017e.web.app/',
      size: 430,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: true,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 537634964,
      node_id: 'R_kgDOIAuolA',
      name: 'translated-content',
      full_name: 'HalefAlmeida/translated-content',
      private: false,
      owner: {
        login: 'HalefAlmeida',
        id: 38929215,
        node_id: 'MDQ6VXNlcjM4OTI5MjE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/38929215?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/HalefAlmeida',
        html_url: 'https://github.com/HalefAlmeida',
        followers_url: 'https://api.github.com/users/HalefAlmeida/followers',
        following_url: 'https://api.github.com/users/HalefAlmeida/following{/other_user}',
        gists_url: 'https://api.github.com/users/HalefAlmeida/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/HalefAlmeida/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/HalefAlmeida/subscriptions',
        organizations_url: 'https://api.github.com/users/HalefAlmeida/orgs',
        repos_url: 'https://api.github.com/users/HalefAlmeida/repos',
        events_url: 'https://api.github.com/users/HalefAlmeida/events{/privacy}',
        received_events_url: 'https://api.github.com/users/HalefAlmeida/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      html_url: 'https://github.com/HalefAlmeida/translated-content',
      description: 'All translated MDN content in raw form',
      fork: true,
      url: 'https://api.github.com/repos/HalefAlmeida/translated-content',
      forks_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/forks',
      keys_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/teams',
      hooks_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/hooks',
      issue_events_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/issues/events{/number}',
      events_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/events',
      assignees_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/branches{/branch}',
      tags_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/tags',
      blobs_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/languages',
      stargazers_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/stargazers',
      contributors_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/contributors',
      subscribers_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/subscribers',
      subscription_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/subscription',
      commits_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/merges',
      archive_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/downloads',
      issues_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/issues{/number}',
      pulls_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/HalefAlmeida/translated-content/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/labels{/name}',
      releases_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/releases{/id}',
      deployments_url: 'https://api.github.com/repos/HalefAlmeida/translated-content/deployments',
      created_at: '2022-09-16T22:17:04Z',
      updated_at: '2022-09-20T00:12:25Z',
      pushed_at: '2022-09-20T01:42:26Z',
      git_url: 'git://github.com/HalefAlmeida/translated-content.git',
      ssh_url: 'git@github.com:HalefAlmeida/translated-content.git',
      clone_url: 'https://github.com/HalefAlmeida/translated-content.git',
      svn_url: 'https://github.com/HalefAlmeida/translated-content',
      homepage: null,
      size: 419330,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Markdown',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'other',
        name: 'Other',
        spdx_id: 'NOASSERTION',
        url: null,
        node_id: 'MDc6TGljZW5zZTA=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
  ];

  const languages = getLangsFrom(repositoriesMock);

  return (
    <Container>
      <Sidebar>
        <Profile user={userMock} />
        <Filter languages={languages} />
      </Sidebar>
      <Main>
        <Repositories />
      </Main>
    </Container>
  );
}
